### ISSUE TITLE
Numpy not support 'isfinite'

### ISSUE THREAD

**Issue by TakuroTsutsumi** [katadori/HenonHeilesDynamics#1]
Resultsの下のセルを実行すると以下のようなエラーが出力されます。
numpy では isfinite が指定できない？ようです。

デバックしようと思いましたが、エラーの場所がよくわかりませんでした。。。

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'

---

![image](https://github.com/katadori/HenonHeilesDynamics/assets/53633304/7dfd7ab3-5f73-406a-811f-bb10083e67fd)

**Comment by katadori** [comment]
バグの報告ありがとうございます．確認し，修正いたしました．

原因としては，当該のndarrayのdtypeがfloatであるべきところ，誤ってsympy objectであったため，エラーを吐いていたようでした．

エネルギー的に取りうる領域を示すにあたり，その上限と下限をsympy.solveにより方程式を解くことで求めています．
この結果が，見た目は数値データなのですが，その実態はdtypeがsympy objectであることを見落としておりました．
このsympy objectに対してfloatを四則演算をすることはできるのですが，np.isinfinete()  （数値の発散等を評価するメソッド）のような処理はできなかったため，エラーになってしまったようです．

おそらく，私のローカル環境とGoogle Colabではnumpyのライブラリのバージョンが違い，過去のバージョンでは許されていたエラー処理が引っかかるようになったのだと思われます......

確認不足で失礼いたしました．
